<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HW5-Fitting Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW5-Fitting Models</h1>
<p class="subtitle lead">Jie Chen 07/14/2024</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The purpose of this homework is to get practice fitting models using the caret package.</p>
<section id="task-1-conceptual-questions" class="level2">
<h2 class="anchored" data-anchor-id="task-1-conceptual-questions">Task 1: Conceptual Questions</h2>
<ol type="1">
<li><p>What is the purpose of using cross-validation when fitting a random forest model?</p>
<p>Cross-validation is essential when fitting a random forest model because it provides a robust way to evaluate the model’s performance, prevents overfitting, helps in hyperparameter tuning, and ensures the model’s reliability and generalizability.</p></li>
<li><p>Describe the bagged tree algorithm.</p>
<p>Generate new training samples (bootstrap sampling) with replacement. Training individual tree and aggregate pridictions. It reduces overfitting, improves accuracy, and provides robustness against noise and outliers, making it a powerful ensemble technique in machine learning.</p></li>
<li><p>What is meant by a general linear model?</p>
<p>A General Linear Model (GLM) is a framework that extends linear regression to model response variables with different types of distributions by using a link function to relate the mean of the response variable to the linear predictor. GLMs are versatile and can be used for various types of data, making them a powerful tool in statistical modeling and analysis.</p></li>
<li><p>When fitting a multiple linear regression model, what does adding an interacion term do? That is , what does it allow the model to do differently as compared to when it is not included in the model?</p>
<p>When fitting a multiple linear regression model, adding an interaction term allows the model to account for the combined effect of two (or more) predictor variables on the response variable. This can be particularly useful when the effect of one predictor variable on the response variable depends on the value of another predictor variable.</p></li>
<li><p>Why do we split our data into a training and test set?</p>
<p>Splitting data into a training set and a test set is essential for assessing the model’s ability to generalize to new data, Preventing overfitting, providing an unbiased evaluation of model performance, avoiding data leakage, ensuring that the model’s performance is evaluated accurately and fairly.</p></li>
</ol>
<section id="task-2-fitting-models" class="level3">
<h3 class="anchored" data-anchor-id="task-2-fitting-models">Task 2: Fitting Models</h3>
<p>Here we use the dataset called heart.csv. The data set gives information about whether or not someone has heart disease (HeartDisease =1 or =0) along with different measurements about that person’s health.</p>
<section id="quick-eda-data-preparation" class="level4">
<h4 class="anchored" data-anchor-id="quick-eda-data-preparation">Quick EDA / Data Preparation</h4>
<p>Loading required packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read in the data first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/online/datasets/heart.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 918 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Sex, ChestPainType, RestingECG, ExerciseAngina, ST_Slope
dbl (7): Age, RestingBP, Cholesterol, FastingBS, MaxHR, Oldpeak, HeartDisease

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>After checking the data, I want to convert the character variables to factors. And also there is a numeric variable FastingBS (0/1) also need to be converted to factor. And then check on the missingness and summarize the data with respect to the relationships of the variables to HeartDisease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert character variables to factors</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> heart_data <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>heart_data<span class="sc">$</span>FastingBS <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(heart_data<span class="sc">$</span>FastingBS)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># check missing values</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(heart_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Data set doesn’t contain any missing values. Then we do some summaries for both numerical and categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary the whole data frame</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heart_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age        Sex     ChestPainType   RestingBP      Cholesterol   
 Min.   :28.00   F:193   ASY:496       Min.   :  0.0   Min.   :  0.0  
 1st Qu.:47.00   M:725   ATA:173       1st Qu.:120.0   1st Qu.:173.2  
 Median :54.00           NAP:203       Median :130.0   Median :223.0  
 Mean   :53.51           TA : 46       Mean   :132.4   Mean   :198.8  
 3rd Qu.:60.00                         3rd Qu.:140.0   3rd Qu.:267.0  
 Max.   :77.00                         Max.   :200.0   Max.   :603.0  
 FastingBS  RestingECG      MaxHR       ExerciseAngina    Oldpeak       
 0:704     LVH   :188   Min.   : 60.0   N:547          Min.   :-2.6000  
 1:214     Normal:552   1st Qu.:120.0   Y:371          1st Qu.: 0.0000  
           ST    :178   Median :138.0                  Median : 0.6000  
                        Mean   :136.8                  Mean   : 0.8874  
                        3rd Qu.:156.0                  3rd Qu.: 1.5000  
                        Max.   :202.0                  Max.   : 6.2000  
 ST_Slope    HeartDisease   
 Down: 63   Min.   :0.0000  
 Flat:460   1st Qu.:0.0000  
 Up  :395   Median :1.0000  
            Mean   :0.5534  
            3rd Qu.:1.0000  
            Max.   :1.0000  </code></pre>
</div>
</div>
<p>Calculate and plot correlation between all numerical features.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>m<span class="ot">=</span> <span class="fu">cor</span>(<span class="fu">select</span>(heart_data,<span class="fu">c</span>(HeartDisease,Age,RestingBP,Cholesterol, MaxHR,Oldpeak)))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(m, <span class="at">method=</span><span class="st">'color'</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">order=</span><span class="st">'alphabet'</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">diag=</span><span class="cn">FALSE</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">col=</span><span class="fu">COL2</span>(<span class="st">'PiYG'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5-Fitting-Models_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It seems person with heart disease has some linear correlation with age, resting blood pressure, serum cholesterol, maximum heart rate and oldpeak.</p>
<p>Now, check on categorical variables vs.&nbsp;HeartDisease</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to summarize a categorical variable by HeartDisease</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>category_summary <span class="ot">&lt;-</span> <span class="cf">function</span>(var){</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  heart_data <span class="sc">|&gt;</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(HeartDisease, {{var}}) <span class="sc">|&gt;</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HeartDisease) <span class="sc">|&gt;</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># gender vs. heartdisease</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>gender_summary <span class="ot">&lt;-</span> <span class="fu">category_summary</span>(Sex)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gender_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   HeartDisease [2]
  HeartDisease Sex       n percentage
         &lt;dbl&gt; &lt;fct&gt; &lt;int&gt;      &lt;dbl&gt;
1            0 F       143      34.9 
2            0 M       267      65.1 
3            1 F        50       9.84
4            1 M       458      90.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chestpain type vs. HeartDisease</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>chestpain_summary <span class="ot">&lt;-</span><span class="fu">category_summary</span>(ChestPainType)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(chestpain_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
# Groups:   HeartDisease [2]
  HeartDisease ChestPainType     n percentage
         &lt;dbl&gt; &lt;fct&gt;         &lt;int&gt;      &lt;dbl&gt;
1            0 ASY             104      25.4 
2            0 ATA             149      36.3 
3            0 NAP             131      32.0 
4            0 TA               26       6.34
5            1 ASY             392      77.2 
6            1 ATA              24       4.72
7            1 NAP              72      14.2 
8            1 TA               20       3.94</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fastingBS vs HeartDisease</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fastingBS_summary <span class="ot">&lt;-</span> <span class="fu">category_summary</span>(FastingBS)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fastingBS_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   HeartDisease [2]
  HeartDisease FastingBS     n percentage
         &lt;dbl&gt; &lt;fct&gt;     &lt;int&gt;      &lt;dbl&gt;
1            0 0           366       89.3
2            0 1            44       10.7
3            1 0           338       66.5
4            1 1           170       33.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># restingECG vs. HeartDisease</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>resting_summary <span class="ot">&lt;-</span> <span class="fu">category_summary</span>(RestingECG)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(resting_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
# Groups:   HeartDisease [2]
  HeartDisease RestingECG     n percentage
         &lt;dbl&gt; &lt;fct&gt;      &lt;int&gt;      &lt;dbl&gt;
1            0 LVH           82       20  
2            0 Normal       267       65.1
3            0 ST            61       14.9
4            1 LVH          106       20.9
5            1 Normal       285       56.1
6            1 ST           117       23.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exerciseangina vs heartdisease</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>exerciseAngina_summary <span class="ot">&lt;-</span><span class="fu">category_summary</span>(ExerciseAngina)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(exerciseAngina_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   HeartDisease [2]
  HeartDisease ExerciseAngina     n percentage
         &lt;dbl&gt; &lt;fct&gt;          &lt;int&gt;      &lt;dbl&gt;
1            0 N                355       86.6
2            0 Y                 55       13.4
3            1 N                192       37.8
4            1 Y                316       62.2</code></pre>
</div>
</div>
<p>From the above summary, Four categorical variables may be related to Heart Disease. Male may has high percentage with heart disease compared to female. Chest pain type with ASY, RestingECG with ST may has higher rate of heart disease. Heart disease is probably also related to exercise induced angina.</p>
<p>Now we want to create a new variable which is a factor version of HeartDisease varible and remove the ST_slope and the original HeartDisease variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> heart_data <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HD=</span><span class="fu">ifelse</span>(HeartDisease<span class="sc">==</span><span class="dv">0</span>,<span class="st">"No"</span>,<span class="st">"Yes"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HD=</span><span class="fu">as.factor</span>(HD))<span class="sc">|&gt;</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>HeartDisease,<span class="sc">-</span>ST_Slope) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will create dummy columns corresponding to the Sex, ExerciseAngina, ChestPainType and RestingECG for use in KNN model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables for categorical columns</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>dummies <span class="ot">&lt;-</span> <span class="fu">dummyVars</span>(<span class="sc">~</span> Sex <span class="sc">+</span> ChestPainType <span class="sc">+</span> RestingECG <span class="sc">+</span> ExerciseAngina, <span class="at">data =</span> heart_data)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the dummy columns</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>dummy_data <span class="ot">&lt;-</span> <span class="fu">predict</span>(dummies, <span class="at">newdata =</span> heart_data)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the dummy data to a data frame</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>dummy_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(dummy_data)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the dummy columns with the original data</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(heart_data, dummy_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s check the data structure</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(heart_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   918 obs. of  22 variables:
 $ Age              : num  40 49 37 48 54 39 45 54 37 48 ...
 $ Sex              : Factor w/ 2 levels "F","M": 2 1 2 1 2 2 1 2 2 1 ...
 $ ChestPainType    : Factor w/ 4 levels "ASY","ATA","NAP",..: 2 3 2 1 3 3 2 2 1 2 ...
 $ RestingBP        : num  140 160 130 138 150 120 130 110 140 120 ...
 $ Cholesterol      : num  289 180 283 214 195 339 237 208 207 284 ...
 $ FastingBS        : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 1 1 ...
 $ RestingECG       : Factor w/ 3 levels "LVH","Normal",..: 2 2 3 2 2 2 2 2 2 2 ...
 $ MaxHR            : num  172 156 98 108 122 170 170 142 130 120 ...
 $ ExerciseAngina   : Factor w/ 2 levels "N","Y": 1 1 1 2 1 1 1 1 2 1 ...
 $ Oldpeak          : num  0 1 0 1.5 0 0 0 0 1.5 0 ...
 $ HD               : Factor w/ 2 levels "No","Yes": 1 2 1 2 1 1 1 1 2 1 ...
 $ Sex.F            : num  0 1 0 1 0 0 1 0 0 1 ...
 $ Sex.M            : num  1 0 1 0 1 1 0 1 1 0 ...
 $ ChestPainType.ASY: num  0 0 0 1 0 0 0 0 1 0 ...
 $ ChestPainType.ATA: num  1 0 1 0 0 0 1 1 0 1 ...
 $ ChestPainType.NAP: num  0 1 0 0 1 1 0 0 0 0 ...
 $ ChestPainType.TA : num  0 0 0 0 0 0 0 0 0 0 ...
 $ RestingECG.LVH   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ RestingECG.Normal: num  1 1 0 1 1 1 1 1 1 1 ...
 $ RestingECG.ST    : num  0 0 1 0 0 0 0 0 0 0 ...
 $ ExerciseAngina.N : num  1 1 1 0 1 1 1 1 0 1 ...
 $ ExerciseAngina.Y : num  0 0 0 1 0 0 0 0 1 0 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="split-the-data" class="level3">
<h3 class="anchored" data-anchor-id="split-the-data">Split the data</h3>
<p>Split the heart_data into training and test set with a 70:30 ratio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span><span class="fu">createDataPartition</span>(heart_data<span class="sc">$</span>HD, <span class="at">p=</span><span class="fl">0.7</span>, <span class="at">list=</span><span class="cn">FALSE</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span>heart_data[trainIndex,]</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span>heart_data[<span class="sc">-</span>trainIndex,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preprocessing-data" class="level3">
<h3 class="anchored" data-anchor-id="preprocessing-data">Preprocessing data</h3>
<p>preprocessing data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>pre_proc_values <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(train_data, <span class="at">method=</span><span class="fu">c</span>(<span class="st">"center"</span>,<span class="st">"scale"</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># scaling and centralizing train and test data sets</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>train_trans <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_proc_values, train_data)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>test_trans <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_proc_values, test_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Training the kNN model, 10 fold cv, repeats =3. We need to standardize our data using caret’s preProcess() method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method=</span><span class="st">"repeatedcv"</span>, <span class="at">number=</span><span class="dv">10</span>, <span class="at">repeats=</span><span class="dv">3</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove unwanted columns</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>train_data_knn <span class="ot">&lt;-</span> train_data <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Sex, <span class="sc">-</span>ChestPainType, <span class="sc">-</span>FastingBS, <span class="sc">-</span>RestingECG, <span class="sc">-</span>ExerciseAngina)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the tuning grid for k values from 1 to 40</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>tune_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">k =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>knn_model <span class="ot">&lt;-</span> <span class="fu">train</span>(HD<span class="sc">~</span> ., </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data=</span>train_data_knn, </span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method=</span><span class="st">"knn"</span>, </span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trControl=</span>train.control,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>                   <span class="at">preProcess=</span><span class="fu">c</span>(<span class="st">'center'</span>,<span class="st">'scale'</span>),</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tuneGrid=</span>tune_grid)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>knn_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>k-Nearest Neighbors 

643 samples
 16 predictor
  2 classes: 'No', 'Yes' 

Pre-processing: centered (16), scaled (16) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 578, 579, 578, 579, 579, 579, ... 
Resampling results across tuning parameters:

  k   Accuracy   Kappa    
   1  0.7751759  0.5479688
   2  0.7813212  0.5594320
   3  0.7907275  0.5777054
   4  0.7979065  0.5927962
   5  0.8109446  0.6198381
   6  0.8056799  0.6093205
   7  0.8020654  0.6019602
   8  0.8062165  0.6101834
   9  0.8035868  0.6048437
  10  0.8057836  0.6089835
  11  0.7995331  0.5963172
  12  0.7948210  0.5867341
  13  0.7958958  0.5891886
  14  0.8005355  0.5983682
  15  0.8015937  0.6003608
  16  0.8062822  0.6093112
  17  0.8026519  0.6023430
  18  0.8005202  0.5982539
  19  0.8088380  0.6142741
  20  0.8119555  0.6205463
  21  0.8134534  0.6238227
  22  0.8088062  0.6138168
  23  0.8088463  0.6142850
  24  0.8124197  0.6217965
  25  0.8088297  0.6141379
  26  0.8114264  0.6191198
  27  0.8072833  0.6107233
  28  0.8124596  0.6207149
  29  0.8057531  0.6070172
  30  0.8124601  0.6198159
  31  0.8104085  0.6162012
  32  0.8166110  0.6284976
  33  0.8181897  0.6311455
  34  0.8166190  0.6281102
  35  0.8191500  0.6331666
  36  0.8191663  0.6330036
  37  0.8197279  0.6340168
  38  0.8202080  0.6349854
  39  0.8181652  0.6307121
  40  0.8181735  0.6308435

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 38.</code></pre>
</div>
</div>
<p>From the results, it automatically selects best k-value. Here, our training model is choosing k = 35 as its final value.</p>
<p>Let’s plot the result</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(knn_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5-Fitting-Models_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As it could be seen from the graph above, k=35 has the highest accuracy.</p>
<p>Now, our model is trained with K value as 35. We are ready to predict classes for our test set. We can use predict() method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>test_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(knn_model, <span class="at">newdata =</span> test_trans)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>test_pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] No  No  No  Yes No  No  No  Yes Yes No  No  No  No  No  Yes No  No  Yes
 [19] Yes No  No  No  Yes Yes No  No  Yes No  Yes Yes No  No  Yes No  No  Yes
 [37] Yes No  Yes No  No  Yes Yes No  Yes Yes No  No  Yes Yes Yes No  Yes No 
 [55] No  No  No  Yes No  No  Yes No  No  Yes Yes No  Yes No  No  No  No  Yes
 [73] Yes Yes Yes Yes Yes No  Yes No  No  Yes Yes No  No  No  No  Yes No  Yes
 [91] Yes Yes Yes Yes Yes Yes Yes No  Yes Yes No  Yes Yes Yes Yes No  Yes Yes
[109] No  Yes No  Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes
[127] No  Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes
[145] Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes
[163] Yes Yes Yes Yes No  No  Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes
[181] Yes No  No  No  Yes Yes Yes Yes No  No  Yes Yes Yes No  Yes No  Yes No 
[199] No  No  No  Yes No  No  Yes No  No  No  Yes No  No  Yes No  Yes Yes Yes
[217] No  No  Yes No  Yes Yes No  Yes No  Yes Yes Yes Yes Yes Yes No  No  No 
[235] No  No  Yes Yes Yes No  Yes Yes No  Yes No  No  No  No  Yes No  No  No 
[253] Yes No  No  No  No  No  Yes No  Yes No  No  No  Yes No  No  Yes No  Yes
[271] No  No  Yes No  No 
Levels: No Yes</code></pre>
</div>
</div>
<p>Check how Accurately our knn model is working? Using confusionMatrix(), we can print statistics of our results. It shows that our model accuracy for test set is 76.36%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(test_pred, test_trans<span class="sc">$</span>HD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   88  30
       Yes  35 122
                                          
               Accuracy : 0.7636          
                 95% CI : (0.7089, 0.8126)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : 3.04e-13        
                                          
                  Kappa : 0.5201          
                                          
 Mcnemar's Test P-Value : 0.6198          
                                          
            Sensitivity : 0.7154          
            Specificity : 0.8026          
         Pos Pred Value : 0.7458          
         Neg Pred Value : 0.7771          
             Prevalence : 0.4473          
         Detection Rate : 0.3200          
   Detection Prevalence : 0.4291          
      Balanced Accuracy : 0.7590          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
</section>
<section id="logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h3>
<p>preprocessing data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove the dummy variables from train and test dataset</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>train_log <span class="ot">&lt;-</span> train_data <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>test_log <span class="ot">&lt;-</span> test_data <span class="sc">|&gt;</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>pre_proc_values <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(train_log, <span class="at">method=</span><span class="fu">c</span>(<span class="st">"center"</span>,<span class="st">"scale"</span>))</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># scaling and centralizing train and test data sets</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>train_trans <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_proc_values, train_log)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>test_trans <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_proc_values, test_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define train control for repeated CV</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Logistic Regression Model</p>
<p>Fitting logistic regression model 1 with all variables from train_trans data set except HD. (dummy variables already removed here)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Model 1</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>glm_model_1 <span class="ot">&lt;-</span> <span class="fu">train</span>(HD <span class="sc">~</span> ., </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> train_trans,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method =</span> <span class="st">"glm"</span>, </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">trControl =</span> train.control,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">metric=</span><span class="st">"Accuracy"</span>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of Model 1</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -0.442834   0.385857  -1.148  0.25111    
Age               0.245449   0.136022   1.804  0.07116 .  
SexM              1.398721   0.311016   4.497 6.88e-06 ***
ChestPainTypeATA -2.079358   0.350565  -5.931 3.00e-09 ***
ChestPainTypeNAP -1.537040   0.284982  -5.393 6.91e-08 ***
ChestPainTypeTA  -1.288983   0.479028  -2.691  0.00713 ** 
RestingBP         0.005698   0.118918   0.048  0.96178    
Cholesterol      -0.348418   0.138046  -2.524  0.01161 *  
FastingBS1        1.332280   0.305616   4.359 1.30e-05 ***
RestingECGNormal -0.244630   0.303653  -0.806  0.42046    
RestingECGST     -0.500140   0.404013  -1.238  0.21574    
MaxHR            -0.325816   0.142386  -2.288  0.02212 *  
ExerciseAnginaY   1.160546   0.273838   4.238 2.25e-05 ***
Oldpeak           0.688956   0.142257   4.843 1.28e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 883.97  on 642  degrees of freedom
Residual deviance: 481.88  on 629  degrees of freedom
AIC: 509.88

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>glm_model_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Linear Model 

643 samples
 10 predictor
  2 classes: 'No', 'Yes' 

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 578, 579, 578, 579, 579, 579, ... 
Resampling results:

  Accuracy   Kappa    
  0.8201684  0.6358332</code></pre>
</div>
</div>
<p>Predict on test data and Check how well this model 1 does on the test set using confusionMatrix(). We find the accuracy is 83.27%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>test_pred_glm_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm_model_1, <span class="at">newdata=</span><span class="fu">select</span>(test_trans, <span class="sc">-</span><span class="fu">c</span>(HD)), <span class="at">type=</span><span class="st">'raw'</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>test_pred_glm_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] No  Yes No  Yes No  No  No  Yes Yes No  No  No  No  No  Yes No  No  No 
 [19] Yes Yes No  No  Yes No  No  No  No  No  Yes No  No  No  No  No  No  Yes
 [37] Yes No  No  No  No  Yes Yes No  Yes No  No  No  Yes Yes Yes No  Yes No 
 [55] No  No  No  Yes No  No  Yes No  No  Yes Yes No  Yes No  No  No  No  No 
 [73] Yes Yes Yes Yes Yes No  Yes No  No  Yes Yes No  No  No  No  Yes No  Yes
 [91] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes
[109] Yes Yes No  Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes
[127] Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes
[145] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes
[163] Yes Yes Yes Yes Yes No  No  No  Yes Yes Yes Yes Yes Yes Yes Yes No  Yes
[181] Yes Yes No  No  Yes Yes Yes Yes No  No  Yes Yes Yes Yes Yes Yes No  No 
[199] No  No  No  Yes No  No  Yes No  No  No  Yes No  No  Yes No  Yes Yes No 
[217] No  No  Yes No  No  Yes Yes Yes No  Yes No  Yes Yes Yes Yes No  Yes Yes
[235] Yes Yes Yes Yes Yes No  Yes Yes No  Yes No  No  No  No  Yes No  No  No 
[253] No  No  No  No  No  Yes No  No  Yes No  No  No  Yes No  No  Yes No  Yes
[271] No  No  Yes Yes No 
Levels: No Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check how well this model does</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(test_pred_glm_1, test_trans<span class="sc">$</span>HD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   97  20
       Yes  26 132
                                          
               Accuracy : 0.8327          
                 95% CI : (0.7833, 0.8749)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.6601          
                                          
 Mcnemar's Test P-Value : 0.461           
                                          
            Sensitivity : 0.7886          
            Specificity : 0.8684          
         Pos Pred Value : 0.8291          
         Neg Pred Value : 0.8354          
             Prevalence : 0.4473          
         Detection Rate : 0.3527          
   Detection Prevalence : 0.4255          
      Balanced Accuracy : 0.8285          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
<p>Logistic Regression Model 2: fiting a model with predictors: Age, Oldpeak, MaxHR, ChestPainType,ExerciseAngina,Cholesterol</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model 2</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define train control for repeated CV</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">5</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>glm_model_2 <span class="ot">&lt;-</span> <span class="fu">train</span>(HD <span class="sc">~</span> Age<span class="sc">+</span>MaxHR<span class="sc">+</span>Oldpeak<span class="sc">+</span>ExerciseAngina<span class="sc">+</span>Cholesterol, </span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> train_trans, </span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method =</span> <span class="st">"glm"</span>, </span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">trControl =</span> train.control,</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">'center'</span>, <span class="st">'scale'</span>))</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of Model 2</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       0.4316     0.1081   3.994 6.51e-05 ***
Age               0.2605     0.1139   2.286 0.022235 *  
MaxHR            -0.4574     0.1187  -3.852 0.000117 ***
Oldpeak           0.7879     0.1290   6.109 1.00e-09 ***
ExerciseAnginaY   0.8038     0.1178   6.826 8.73e-12 ***
Cholesterol      -0.6024     0.1147  -5.252 1.50e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 883.97  on 642  degrees of freedom
Residual deviance: 587.20  on 637  degrees of freedom
AIC: 599.2

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>glm_model_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Linear Model 

643 samples
  5 predictor
  2 classes: 'No', 'Yes' 

Pre-processing: centered (5), scaled (5) 
Resampling: Cross-Validated (5 fold, repeated 3 times) 
Summary of sample sizes: 515, 514, 514, 515, 514, 514, ... 
Resampling results:

  Accuracy   Kappa    
  0.8060309  0.6087954</code></pre>
</div>
</div>
<p>Predict on test data and Check how well this model does on the test set using confusionMatrix(). We find the accuracy is 80%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>test_pred_glm_2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm_model_2, <span class="at">newdata=</span><span class="fu">select</span>(test_trans, <span class="sc">-</span><span class="fu">c</span>(HD)), <span class="at">type=</span><span class="st">'raw'</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>test_pred_glm_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] No  Yes No  Yes No  No  No  Yes Yes No  No  No  No  No  Yes Yes No  No 
 [19] Yes Yes No  No  Yes No  No  No  No  No  Yes No  No  No  No  No  No  No 
 [37] No  Yes No  Yes No  Yes Yes No  Yes No  No  No  Yes Yes Yes No  No  No 
 [55] No  No  No  Yes No  No  Yes No  No  No  No  No  No  Yes No  No  No  No 
 [73] Yes Yes Yes Yes Yes No  Yes No  No  Yes Yes No  No  Yes No  No  No  Yes
 [91] Yes Yes Yes Yes Yes No  Yes Yes Yes Yes No  No  Yes Yes Yes Yes Yes Yes
[109] Yes Yes Yes Yes Yes Yes Yes No  No  Yes Yes Yes Yes Yes Yes Yes Yes Yes
[127] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes
[145] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes
[163] Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes Yes No  No 
[181] Yes Yes No  No  No  No  Yes Yes No  Yes Yes No  Yes Yes Yes Yes No  Yes
[199] No  No  No  Yes No  No  Yes Yes Yes No  No  No  No  Yes No  Yes No  No 
[217] No  No  Yes No  No  Yes Yes Yes No  Yes No  Yes Yes Yes Yes No  Yes Yes
[235] No  Yes Yes Yes No  No  No  Yes No  No  No  No  No  Yes Yes No  Yes No 
[253] Yes No  No  No  No  Yes No  No  Yes No  No  No  Yes No  No  Yes No  Yes
[271] No  No  Yes Yes No 
Levels: No Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check how well this model does</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(test_pred_glm_2, test_trans<span class="sc">$</span>HD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   94  26
       Yes  29 126
                                          
               Accuracy : 0.8             
                 95% CI : (0.7478, 0.8456)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.5946          
                                          
 Mcnemar's Test P-Value : 0.7874          
                                          
            Sensitivity : 0.7642          
            Specificity : 0.8289          
         Pos Pred Value : 0.7833          
         Neg Pred Value : 0.8129          
             Prevalence : 0.4473          
         Detection Rate : 0.3418          
   Detection Prevalence : 0.4364          
      Balanced Accuracy : 0.7966          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
<p>Logistic Regression Model 3: fiting a model only with predictors Age and MaxHR interaction term,Oldpeak,ChestPainType,ExerciseAngina</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model 3</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define train control for repeated CV</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">5</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>glm_model_3 <span class="ot">&lt;-</span> <span class="fu">train</span>(HD <span class="sc">~</span> Age<span class="sc">*</span>MaxHR <span class="sc">+</span> Oldpeak<span class="sc">+</span> Cholesterol<span class="sc">+</span>ExerciseAngina, </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> train_trans, </span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method =</span> <span class="st">"glm"</span>, </span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">trControl =</span> train.control,</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">'center'</span>, <span class="st">'scale'</span>))</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary of Model 3</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_model_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      0.43624    0.10958   3.981 6.86e-05 ***
Age              0.26617    0.11615   2.292 0.021925 *  
MaxHR           -0.45963    0.11915  -3.857 0.000115 ***
Oldpeak          0.78812    0.12902   6.108 1.01e-09 ***
Cholesterol     -0.60093    0.11491  -5.230 1.70e-07 ***
ExerciseAnginaY  0.80455    0.11784   6.827 8.66e-12 ***
`Age:MaxHR`     -0.03058    0.11818  -0.259 0.795848    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 883.97  on 642  degrees of freedom
Residual deviance: 587.14  on 636  degrees of freedom
AIC: 601.14

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>glm_model_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Linear Model 

643 samples
  5 predictor
  2 classes: 'No', 'Yes' 

Pre-processing: centered (6), scaled (6) 
Resampling: Cross-Validated (5 fold, repeated 3 times) 
Summary of sample sizes: 515, 514, 514, 515, 514, 514, ... 
Resampling results:

  Accuracy   Kappa    
  0.8049972  0.6066332</code></pre>
</div>
</div>
<p>Predict on test data and Check how well this model does on the test set using confusionMatrix(). We find the accuracy is 79.64%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>test_pred_glm_3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm_model_3, <span class="at">newdata=</span><span class="fu">select</span>(test_trans, <span class="sc">-</span><span class="fu">c</span>(HD)), <span class="at">type=</span><span class="st">'raw'</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>test_pred_glm_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] No  Yes No  Yes No  No  No  Yes Yes No  No  No  No  No  Yes Yes No  No 
 [19] Yes Yes No  No  Yes No  No  No  No  No  Yes No  No  No  No  No  No  No 
 [37] No  Yes No  Yes No  Yes Yes No  Yes No  No  No  Yes Yes Yes No  No  No 
 [55] No  No  No  Yes No  No  Yes No  No  No  No  No  No  Yes No  No  No  No 
 [73] Yes Yes Yes Yes Yes No  Yes No  No  Yes Yes No  No  Yes No  No  No  Yes
 [91] Yes Yes No  Yes Yes No  Yes Yes Yes Yes No  No  Yes Yes Yes Yes Yes Yes
[109] Yes Yes Yes Yes Yes Yes Yes No  No  Yes Yes Yes Yes Yes Yes Yes Yes Yes
[127] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes
[145] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes
[163] Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes Yes No  No 
[181] Yes Yes No  No  No  No  Yes Yes No  Yes Yes No  Yes Yes Yes Yes No  Yes
[199] No  No  No  Yes No  No  Yes Yes Yes No  No  No  No  Yes No  Yes No  No 
[217] No  No  Yes No  No  Yes Yes Yes No  Yes No  Yes Yes Yes Yes No  Yes Yes
[235] No  Yes Yes Yes No  No  No  Yes No  No  No  No  No  Yes Yes No  Yes No 
[253] Yes No  No  No  No  Yes No  No  Yes No  No  No  Yes No  No  Yes No  Yes
[271] No  No  Yes Yes No 
Levels: No Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check how well this model does</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(test_pred_glm_3, test_trans<span class="sc">$</span>HD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   94  27
       Yes  29 125
                                          
               Accuracy : 0.7964          
                 95% CI : (0.7439, 0.8424)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.5875          
                                          
 Mcnemar's Test P-Value : 0.8937          
                                          
            Sensitivity : 0.7642          
            Specificity : 0.8224          
         Pos Pred Value : 0.7769          
         Neg Pred Value : 0.8117          
             Prevalence : 0.4473          
         Detection Rate : 0.3418          
   Detection Prevalence : 0.4400          
      Balanced Accuracy : 0.7933          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
<p>From the above three logistic regression model, the best model of them is the model with full predictors</p>
<p>Predict on test data and Check how well this model 1 does on the test set using confusionMatrix(). We find the accuracy is 83.27%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>test_pred_glm_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm_model_1, <span class="at">newdata=</span><span class="fu">select</span>(test_trans, <span class="sc">-</span><span class="fu">c</span>(HD)), <span class="at">type=</span><span class="st">'raw'</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>test_pred_glm_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] No  Yes No  Yes No  No  No  Yes Yes No  No  No  No  No  Yes No  No  No 
 [19] Yes Yes No  No  Yes No  No  No  No  No  Yes No  No  No  No  No  No  Yes
 [37] Yes No  No  No  No  Yes Yes No  Yes No  No  No  Yes Yes Yes No  Yes No 
 [55] No  No  No  Yes No  No  Yes No  No  Yes Yes No  Yes No  No  No  No  No 
 [73] Yes Yes Yes Yes Yes No  Yes No  No  Yes Yes No  No  No  No  Yes No  Yes
 [91] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes
[109] Yes Yes No  Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes
[127] Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes
[145] Yes Yes Yes Yes Yes Yes Yes Yes Yes Yes No  Yes Yes Yes Yes Yes Yes Yes
[163] Yes Yes Yes Yes Yes No  No  No  Yes Yes Yes Yes Yes Yes Yes Yes No  Yes
[181] Yes Yes No  No  Yes Yes Yes Yes No  No  Yes Yes Yes Yes Yes Yes No  No 
[199] No  No  No  Yes No  No  Yes No  No  No  Yes No  No  Yes No  Yes Yes No 
[217] No  No  Yes No  No  Yes Yes Yes No  Yes No  Yes Yes Yes Yes No  Yes Yes
[235] Yes Yes Yes Yes Yes No  Yes Yes No  Yes No  No  No  No  Yes No  No  No 
[253] No  No  No  No  No  Yes No  No  Yes No  No  No  Yes No  No  Yes No  Yes
[271] No  No  Yes Yes No 
Levels: No Yes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check how well this model does</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(test_pred_glm_1, test_trans<span class="sc">$</span>HD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   97  20
       Yes  26 132
                                          
               Accuracy : 0.8327          
                 95% CI : (0.7833, 0.8749)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.6601          
                                          
 Mcnemar's Test P-Value : 0.461           
                                          
            Sensitivity : 0.7886          
            Specificity : 0.8684          
         Pos Pred Value : 0.8291          
         Neg Pred Value : 0.8354          
             Prevalence : 0.4473          
         Detection Rate : 0.3527          
   Detection Prevalence : 0.4255          
      Balanced Accuracy : 0.8285          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
</section>
<section id="tree-models" class="level3">
<h3 class="anchored" data-anchor-id="tree-models">Tree Models</h3>
<p>Classification tree model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define train control for repeated CV</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the tuning grid for cp</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>tune_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="at">by =</span> <span class="fl">0.001</span>))</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the classification tree model using rpart</span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>classification_tree_model <span class="ot">&lt;-</span> <span class="fu">train</span>(HD <span class="sc">~</span> Age<span class="sc">+</span>MaxHR<span class="sc">+</span>Oldpeak<span class="sc">+</span>ExerciseAngina<span class="sc">+</span>Cholesterol, </span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> train_trans, </span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"rpart"</span>, </span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>                    <span class="at">trControl =</span> train.control,</span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>                    <span class="at">tuneGrid =</span> tune_grid,</span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>                    <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">'center'</span>, <span class="st">'scale'</span>))</span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the fitted model</span></span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(classification_tree_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

643 samples
  5 predictor
  2 classes: 'No', 'Yes' 

Pre-processing: centered (5), scaled (5) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 578, 579, 578, 579, 579, 579, ... 
Resampling results across tuning parameters:

  cp     Accuracy   Kappa    
  0.000  0.7812954  0.5562248
  0.001  0.7880753  0.5699020
  0.002  0.7942532  0.5826704
  0.003  0.7947820  0.5840292
  0.004  0.7989489  0.5929036
  0.005  0.7989489  0.5929036
  0.006  0.7989409  0.5928546
  0.007  0.8004874  0.5959328
  0.008  0.7973862  0.5903817
  0.009  0.7973862  0.5903817
  0.010  0.7994537  0.5945527
  0.011  0.7994537  0.5945527
  0.012  0.7978992  0.5915408
  0.013  0.7978992  0.5908689
  0.014  0.7952785  0.5846323
  0.015  0.7957994  0.5858795
  0.016  0.7927064  0.5794447
  0.017  0.7927064  0.5794447
  0.018  0.7833710  0.5618118
  0.019  0.7833710  0.5618118
  0.020  0.7776408  0.5491216
  0.021  0.7776408  0.5491216
  0.022  0.7735142  0.5427478
  0.023  0.7735142  0.5427478
  0.024  0.7740593  0.5437289
  0.025  0.7740593  0.5437289
  0.026  0.7740673  0.5441850
  0.027  0.7740673  0.5441850
  0.028  0.7771763  0.5521269
  0.029  0.7766555  0.5514626
  0.030  0.7781939  0.5549239
  0.031  0.7803103  0.5596890
  0.032  0.7823616  0.5641805
  0.033  0.7823616  0.5641805
  0.034  0.7823616  0.5641805
  0.035  0.7823616  0.5641805
  0.036  0.7823616  0.5641805
  0.037  0.7823616  0.5641805
  0.038  0.7823616  0.5641805
  0.039  0.7828825  0.5658989
  0.040  0.7828825  0.5658989
  0.041  0.7828825  0.5658989
  0.042  0.7828825  0.5658989
  0.043  0.7828825  0.5658989
  0.044  0.7828825  0.5658989
  0.045  0.7828825  0.5658989
  0.046  0.7828825  0.5658989
  0.047  0.7828825  0.5658989
  0.048  0.7828825  0.5658989
  0.049  0.7828825  0.5658989
  0.050  0.7828825  0.5658989
  0.051  0.7828825  0.5658989
  0.052  0.7828825  0.5658989
  0.053  0.7828825  0.5658989
  0.054  0.7828825  0.5658989
  0.055  0.7828825  0.5658989
  0.056  0.7828825  0.5658989
  0.057  0.7828825  0.5658989
  0.058  0.7828825  0.5658989
  0.059  0.7828825  0.5658989
  0.060  0.7828825  0.5658989
  0.061  0.7828825  0.5658989
  0.062  0.7828825  0.5658989
  0.063  0.7828825  0.5658989
  0.064  0.7828825  0.5658989
  0.065  0.7828825  0.5658989
  0.066  0.7828825  0.5658989
  0.067  0.7828825  0.5658989
  0.068  0.7828825  0.5658989
  0.069  0.7828825  0.5658989
  0.070  0.7828825  0.5658989
  0.071  0.7828825  0.5658989
  0.072  0.7828825  0.5658989
  0.073  0.7828825  0.5658989
  0.074  0.7828825  0.5658989
  0.075  0.7828825  0.5658989
  0.076  0.7828825  0.5658989
  0.077  0.7828825  0.5658989
  0.078  0.7828825  0.5658989
  0.079  0.7828825  0.5658989
  0.080  0.7828825  0.5658989
  0.081  0.7828825  0.5658989
  0.082  0.7828825  0.5658989
  0.083  0.7828825  0.5658989
  0.084  0.7828825  0.5658989
  0.085  0.7828825  0.5658989
  0.086  0.7828825  0.5658989
  0.087  0.7828825  0.5658989
  0.088  0.7828825  0.5658989
  0.089  0.7828825  0.5658989
  0.090  0.7828825  0.5658989
  0.091  0.7828825  0.5658989
  0.092  0.7828825  0.5658989
  0.093  0.7828825  0.5658989
  0.094  0.7828825  0.5658989
  0.095  0.7828825  0.5658989
  0.096  0.7828825  0.5658989
  0.097  0.7828825  0.5658989
  0.098  0.7828825  0.5658989
  0.099  0.7828825  0.5658989
  0.100  0.7828825  0.5658989

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.007.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>test_pred_class_tree <span class="ot">&lt;-</span> <span class="fu">predict</span>(classification_tree_model, test_trans)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model performance on the test set using confusionMatrix</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>conf_matrix_class_tree <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(test_pred_class_tree, test_trans<span class="sc">$</span>HD)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>conf_matrix_class_tree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   89  25
       Yes  34 127
                                          
               Accuracy : 0.7855          
                 95% CI : (0.7322, 0.8325)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : 6.355e-16       
                                          
                  Kappa : 0.563           
                                          
 Mcnemar's Test P-Value : 0.2976          
                                          
            Sensitivity : 0.7236          
            Specificity : 0.8355          
         Pos Pred Value : 0.7807          
         Neg Pred Value : 0.7888          
             Prevalence : 0.4473          
         Detection Rate : 0.3236          
   Detection Prevalence : 0.4145          
      Balanced Accuracy : 0.7796          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
<p>Random Forest</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the number of predictors</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>num_predictors <span class="ot">&lt;-</span> <span class="fu">ncol</span>(train_trans) <span class="sc">-</span> <span class="dv">1</span>  <span class="co"># subtract 1 for the response variable</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the tuning grid for mtry</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>tune_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">mtry =</span> <span class="dv">1</span><span class="sc">:</span>num_predictors)</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the random forest model using rf</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>rf_model <span class="ot">&lt;-</span> <span class="fu">train</span>(HD <span class="sc">~</span> ., </span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> train_trans, </span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rf"</span>, </span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> train.control,</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> tune_grid,</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">'center'</span>, <span class="st">'scale'</span>))</span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the fitted model</span></span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rf_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest 

643 samples
 10 predictor
  2 classes: 'No', 'Yes' 

Pre-processing: centered (13), scaled (13) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 578, 578, 578, 578, 580, 580, ... 
Resampling results across tuning parameters:

  mtry  Accuracy   Kappa    
   1    0.8289831  0.6529171
   2    0.8212179  0.6386347
   3    0.8160251  0.6273581
   4    0.8134365  0.6223002
   5    0.8108892  0.6170886
   6    0.8072017  0.6096151
   7    0.8041581  0.6034965
   8    0.8036205  0.6024262
   9    0.7989485  0.5931307
  10    0.7989891  0.5931999

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was mtry = 1.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>test_pred_rf <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_model, test_trans)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model performance on the test set using confusionMatrix</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>conf_matrix_rf <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(test_pred_rf, test_trans<span class="sc">$</span>HD)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix_rf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   96  17
       Yes  27 135
                                          
               Accuracy : 0.84            
                 95% CI : (0.7912, 0.8813)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.6739          
                                          
 Mcnemar's Test P-Value : 0.1748          
                                          
            Sensitivity : 0.7805          
            Specificity : 0.8882          
         Pos Pred Value : 0.8496          
         Neg Pred Value : 0.8333          
             Prevalence : 0.4473          
         Detection Rate : 0.3491          
   Detection Prevalence : 0.4109          
      Balanced Accuracy : 0.8343          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
<p>Boosted Tree</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the tuning grid</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>tune_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.trees =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>),</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">interaction.depth =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">shrinkage =</span> <span class="fl">0.1</span>,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.minobsinnode =</span> <span class="dv">10</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Define train control for repeated CV</span></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the boosted tree model using gbm</span></span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>gbm_model <span class="ot">&lt;-</span> <span class="fu">train</span>(HD <span class="sc">~</span> ., </span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> train_trans, </span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"gbm"</span>, </span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trControl =</span> train.control,</span>
<span id="cb70-20"><a href="#cb70-20" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tuneGrid =</span> tune_grid,</span>
<span id="cb70-21"><a href="#cb70-21" aria-hidden="true" tabindex="-1"></a>                   <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb70-22"><a href="#cb70-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-23"><a href="#cb70-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the fitted model</span></span>
<span id="cb70-24"><a href="#cb70-24" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gbm_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stochastic Gradient Boosting 

643 samples
 10 predictor
  2 classes: 'No', 'Yes' 

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 578, 579, 578, 579, 579, 579, ... 
Resampling results across tuning parameters:

  interaction.depth  n.trees  Accuracy   Kappa    
  1                   25      0.8062654  0.6070407
  1                   50      0.8259058  0.6470879
  1                  100      0.8248399  0.6455533
  1                  200      0.8237734  0.6433587
  2                   25      0.8206559  0.6359390
  2                   50      0.8300081  0.6559006
  2                  100      0.8320429  0.6600643
  2                  200      0.8232037  0.6423344
  3                   25      0.8222760  0.6397999
  3                   50      0.8243754  0.6448427
  3                  100      0.8305122  0.6565533
  3                  200      0.8227315  0.6407222

Tuning parameter 'shrinkage' was held constant at a value of 0.1

Tuning parameter 'n.minobsinnode' was held constant at a value of 10
Accuracy was used to select the optimal model using the largest value.
The final values used for the model were n.trees = 100, interaction.depth =
 2, shrinkage = 0.1 and n.minobsinnode = 10.</code></pre>
</div>
</div>
<p>The optimal model parameters were found to be n.trees = 100, interaction.depth = 2, shrinkage = 0.1, and n.minobsinnode = 10. This model is expected to provide the best performance based on the accuracy metric.</p>
<p>Evaluate the Boosted Tree Model Using Confusion Matrix</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>test_pred_gbm <span class="ot">&lt;-</span> <span class="fu">predict</span>(gbm_model, test_trans)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model performance on the test set using confusionMatrix</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>conf_matrix_gbm <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(test_pred_gbm, test_trans<span class="sc">$</span>HD)</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix_gbm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No   97  23
       Yes  26 129
                                          
               Accuracy : 0.8218          
                 95% CI : (0.7714, 0.8652)
    No Information Rate : 0.5527          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.6388          
                                          
 Mcnemar's Test P-Value : 0.7751          
                                          
            Sensitivity : 0.7886          
            Specificity : 0.8487          
         Pos Pred Value : 0.8083          
         Neg Pred Value : 0.8323          
             Prevalence : 0.4473          
         Detection Rate : 0.3527          
   Detection Prevalence : 0.4364          
      Balanced Accuracy : 0.8187          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
<p>Among the Tree Models, accuracy of classfication tree model, random forest, boosted tree model is 0.7855, 0.84, 0.8218 respectively. Thus, the random forest model did the best job among these three models.</p>
</section>
<section id="model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison">Model Comparison</h3>
<p>Accuracy of kNN model on the test set is 0.8286. Accuracy of Logistic Regression Model 1 on the test set is 0.8327. Accuracy of the best Tree Model is random forest model which has an accuracy of 0.84. In conclusion, random forest model did the best job in terms of accuracy on the test set.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>